spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: backend
          uri: http://localhost:9090
          predicates:
            - Path=/bff/**
          filters:
            - StripPrefix=1
        - id: frontend
          uri: http://localhost:4200
          predicates:
            - Path=/angular/**
server:
  port: 9050