spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
#removed secrets
            scope:
              - openid
              - profile
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:9090/login/oauth2/code/keycloak
          google:
#removed secerets
        provider:
          keycloak:
            issuerUri: http://localhost:8080/realms/test
#  main:
#    web-application-type: reactive
  application:
    name: bffGateway
  cloud:
    gateway:
      routes:
        - id: resource
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay
            - SaveSession
            - StripPrefix=1
        - id: frontend
          uri: http://localhost:4200
          predicates:
            - Path=/angular/**
server:
  port: 9090
bff:
  baseUrl: http://localhost
  gateway-port: 9050
  gateway-prefix: bff
  auth:
#    login-page: ${bff.baseUrl}:${bff.gateway-port}/${bff.gateway-prefix}/oauth2/authorization/client
    postLogoutRedirect: http://localhost:9090/angular/
#    postLogoutRedirect: ${bff.baseUrl}:${bff.gateway-port}/angular
#    postLoginRedirect: ${bff.baseUrl}:${bff.gateway-port}/angular
#    postLoginRedirect: http://localhost:9090/angular/