spring:
  application:
    name: Bff
  datasource:
    url: jdbc:h2:mem:bff
    driver-class-name: org.h2.Driver
    username: pa
    password: pass
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: servlet
            clientSecret: QLRVlPG6A5fZi4geV97FyI0irgtZBDRL
            scope:
              - openid
              - profile
            authorizationGrantType: authorization_code
            redirectUri: ${bff.baseUrl}:${bff.gateway-port}/${bff.gateway-prefix}/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuerUri: http://localhost:8080/realms/test
server:
  port: 9090
bff:
  baseUrl: http://localhost
  gateway-port: 9050
  gateway-prefix: bff
  auth:
    login-page: ${bff.baseUrl}:${bff.gateway-port}/${bff.gateway-prefix}/oauth2/authorization/client
    postLogoutRedirect: ${bff.baseUrl}:${bff.gateway-port}/angular
    postLoginRedirect: ${bff.baseUrl}:${bff.gateway-port}/angular